name: Actualizar resultados

on:
  schedule:
    - cron: '*/6* * * *'   # cada 6 minutos
  workflow_dispatch:          # permite ejecutar manualmente

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install node-fetch@2 jsonwebtoken

      - name: Ejecutar actualización
        env:
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
        run: node updateMatches.js
